#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift "#{File.dirname(__FILE__)}/../lib"

require 'inkstats'
require 'thor'

class Cli < Thor
  desc 'init', 'Create schema'
  def init
    storage.create_schema!
  end

  desc 'upload', 'Upload latest games'
  def upload
    data = extractor.fetch_battles
    data = JSON.parse File.read('spec/data/battles.json')
    battles = parser.parse data
    require "pry";binding.pry
    # inserted = storage.save battles

    puts "[+] Inserted #{inserted} battles"
  end

  no_commands do
    def storage
      Inkstats::Storage.new
    end

    def parser
      Inkstats::Parser.new
    end

    def extractor
      Inkstats::Extractor.new '6de06a709b77c4416ff8a739c4cac938ac080bb0'
    end
  end
end

Cli.start ARGV
