#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift "#{File.dirname(__FILE__)}/../lib"

require 'inkstats'
require 'thor'

class Cli < Thor
  desc 'upload', 'Upload latest games'
  def upload
    # battles = extractor.fetch_battles
    data = JSON.parse File.read('spec/data/battles.json')
    battles = parser.parse data
    storage.save battles

    puts battles.size
  end

  no_commands do
    def storage
    end

    def parser
      Inkstats::Parser.new
    end

    def extractor
      Inkstats::Extractor.new 'ebb3e0c264fd267aeaa0c6585089216e19e7f01f'
    end
  end
end

Cli.start ARGV
